// Build: player bundle (embedded into exports) -> app bundle.
//   node build.mjs          one-off build into dist/
//   node build.mjs --watch  rebuild the app on change
import { build, context } from "esbuild"
import { mkdirSync, writeFileSync } from "node:fs"

const watch = process.argv.includes("--watch")

// 1. the standalone player, as a string the app writes into exported HTML
const player = await build({
    entryPoints: ["src/player.ts"],
    bundle: true,
    minify: true,
    format: "iife",
    globalName: "PixelArtPlayer",
    target: "es2019",
    write: false,
})
mkdirSync("src/generated", { recursive: true })
writeFileSync(
    "src/generated/player-bundle.ts",
    "// generated by build.mjs, do not edit\nexport default " +
        JSON.stringify(player.outputFiles[0].text) +
        "\n"
)

// 2. the creator app
const options = {
    entryPoints: ["src/app.tsx"],
    bundle: true,
    minify: !watch,
    format: "iife",
    target: "es2019",
    outfile: "dist/app.js",
    define: { "process.env.NODE_ENV": watch ? '"development"' : '"production"' },
    logLevel: "info",
}
if (watch) {
    const ctx = await context(options)
    await ctx.watch()
} else {
    await build(options)
}
